jasypt:
   encryptor:
      password: ${jasyptpwd:secretkey}
      algorithm: PBEWithMD5AndDES

server:
   port: 8080
   servlet:
      context-path: /CeibaEntregas
      session:
         timeout: 21600s

spring:
   datasource:
      driver-class-name: org.h2.Driver
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:h2:mem:ceiba-entregadb
      username: ceibaentrega
      password: ceiba123
      hikari:
         poolName: pool
